version: "3"

services:
  bnetd:
    image: pvpgn-server:bnetd-mysql
    restart: unless-stopped
    ports:
      - 6112:6112/udp
      - 6112:6112
    volumes:
      - /your/config/dir:/usr/local/etc/pvpgn
      - /your/asset/dir:/usr/local/var/pvpgn
  
  d2cs:
    image: pvpgn-server:d2cs-mysql
    restart: unless-stopped
    ports:
      - 6113:6113/udp
      - 6113:6113
    environment: 
      SERVER_TYPE: d2cs 
    volumes:
      - /your/config/dir:/usr/local/etc/pvpgn
      - /your/asset/dir:/usr/local/var/pvpgn

  d2dbs:
    image: pvpgn-server:d2dbs-mysql
    restart: unless-stopped
    ports:
      - 6114:6114/udp
      - 6114:6114
    environment:
      SERVER_TYPE: d2dbs 
    volumes:
      - /your/config/dir:/usr/local/etc/pvpgn
      - /your/asset/dir:/usr/local/var/pvpgn

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: pvpgn-bnetd
      MYSQL_USER: bnetd
      MYSQL_PASSWORD: example
    volumes:
      - /your/db/storage:/var/lib/mysql